name: 'auto-merger'
description: 'Automatically merge PR when all approved and ready'
author: 'Tlaster'
inputs:
  ready_label:
    description: 'label to add to PR when ready for review'
    default: 'ready'
  approved_label:
    description: 'label to add to PR when all approved'
    default: 'approved'
runs:
  using: 'node16'
  main: 'dist/index.js'
